# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-24 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_newvideodescription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewVideoDescription',
        ),
        migrations.AddField(
            model_name='newvideo',
            name='predicted_moods',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AddField(
            model_name='newvideo',
            name='video_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
